CREATE TABLE interaction_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(32) NOT NULL,
    message VARCHAR(120),
    x_coordinate DOUBLE PRECISION,
    y_coordinate DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_interaction_events_created_at
    ON interaction_events (created_at DESC);
